language: go

go:
  - 1.10.x
  - tip

before_install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/haya14busa/goverage

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - goverage -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
